config/routes.rb
Rails.application.routes.draw do
  resources :papers

  root 'papers#home'

  get 'search', to: 'search#search'

end

app/models/paper.rb
require 'elasticsearch/model'

class Paper < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  scope :order_by_views_count, -> {order("views_count desc")}
end
Paper.import # for auto sync model with elastic search

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all.order_by_views_count
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    current_views_count = @paper.views_count.to_i
    @paper.views_count = current_views_count + 1
    @paper.save
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :content, :views_count, :author_name, :original_link)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @papers = []
    else
      @papers = Paper.search params[:q]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YeePaper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Wrap all page content here -->
  <div id="wrap">
    <%= render 'shared/navigation' %>
    <!-- Begin page content -->
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <%= render 'shared/footer' %>

</body>
</html>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "原文作者" %><br>
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label "原文链接" %><br>
    <%= f.text_field :original_link %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/home.html.erb
<p id="notice"><%= notice %></p>

<div class="search-container">
  <h1><img alt="Brand" src="logo.png" class="logo"></h1>

  <div class="row">
    <div class="col-lg-6">
      <form action="/search" method="get">
        <div class="input-group">
          <input type="text" name="q" value="<%= params[:q] %>" placeholder="译文献，易研究" class="form-control" />
          <span class="input-group-btn">
            <button type="submit" name="YeePaper" class="btn btn-default">YeePaper</button>
          </span>
        </div>
      </form>
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
</div>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>
<h1>所有论文</h1>
<ul class="search-lists">
  <% @papers.each do |paper| %>
  <li class="search-list">
    <h3>
      <%= link_to paper.title, paper_path(paper) %>
    </h3>
    <p><i class="fa fa-user"></i> <%= paper.author_name %> <i class="fa fa-eye"></i> <%= paper.views_count %></p>
    <div class="search-content"><%= markdown(paper.content) %></div>
  </li>
  <% end %>
</ul>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @paper.title %>
</h3>
<p>
  <i class="fa fa-user"></i> <%= @paper.author_name %>
  <i class="fa fa-eye"></i> <%= @paper.views_count %>
</p>

<div class="paper-content"><%= markdown(@paper.content) %></div>

<p>
  <i class="fa fa-link"></i> 原文链接：<a href="<%= @paper.original_link %>" target="_blank"><%= @paper.original_link %></a>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %> |
<%= link_to 'Destroy', @paper, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/search/search.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for search_path, :html => { :class => "search-form" }, method: :get do |f| %>
      <div class="input-group">
        <%= text_field_tag :q, params[:q], :placeholder => "译文献，易研究", :class=>"form-control" %>

        <span class="input-group-btn">
          <%= submit_tag "YeePaper", name: nil, :class=>"btn btn-default" %>
        </span>
      </div><!-- /input-group -->
    <% end %>
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<ul class="search-lists">
  <% @papers.each do |paper| %>
  <li class="search-list">
    <h3>
      <%= link_to paper.title, controller: "papers", action: "show", id: paper._id%>
    </h3>
    <p><i class="fa fa-user"></i> <%= paper.author_name %> <i class="fa fa-eye"></i> <%= paper.views_count %></p>

    <div class="search-content"><%= markdown(paper.content) %></div>
  </li>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer id="footer">
  <div class="container">
    <p class="text-muted">&copy; 2015 YeePaper &nbsp;&nbsp;联系我们：hi@yeepaper.cc</p>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">YeePaper</a>
      <%= link_to '创建论文', new_paper_path, :class => "navbar-brand" %>
      <%= link_to '所有论文', papers_path, :class => "navbar-brand" %>
    </div>
  </div><!-- /.container -->
</nav>